"""Add fields to SalesVoucherGroup

Revision ID: 2ca49db6844b
Revises: 4cac2618d12b
Create Date: 2025-01-02 22:55:59.942893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2ca49db6844b'
down_revision = '4cac2618d12b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_voucher_group', schema=None) as batch_op:
        batch_op.add_column(sa.Column('salesperson_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('partner_company', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.create_foreign_key('fk_salesvoucher_salesperson', 'users', ['salesperson_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_voucher_group', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('status')
        batch_op.drop_column('partner_company')
        batch_op.drop_column('salesperson_id')

    # ### end Alembic commands ###
