"""Allow booking_name and cascade delete

Revision ID: b8b554bd90c9
Revises: 2ca49db6844b
Create Date: 2025-01-03 01:18:06.419058

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b8b554bd90c9'
down_revision = '2ca49db6844b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('booking_name', sa.String(length=100), nullable=True))
        batch_op.alter_column('voucher_group_sale_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               nullable=True)
        

    with op.batch_alter_table('sales_voucher_group', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales_voucher_group', schema=None) as batch_op:
        batch_op.alter_column('product_name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)

    with op.batch_alter_table('bookings', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'sales_voucher_group', ['voucher_group_sale_id'], ['id'])
        batch_op.alter_column('booking_date',
               existing_type=sa.DATE(),
               nullable=False)
        batch_op.alter_column('voucher_group_sale_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('booking_name')

    # ### end Alembic commands ###
